### ISSUE TITLE
DeepCreamPyV2 and Monetization

### ISSUE THREAD

**Issue by deeppomf** [deeppomf/DeepCreamPy#117]
(This is not an April Fools joke.)

To cut to the chase, structural changes in the company I work at lead me to believe there will be layoffs soon.
Because I am unsure if I keep my position, I have to prepare for the worst if I am laid off so DeepCreamPyV2 will be monetized in some manner.

Initial thoughts:
1. A free version of DeepCreamPyV2 should be accessible in some form.
2. Many options other open source projects have are not possible for DeepCreamPyV2. Sponsorship by a company, consulting, writing documentation, and selling support do not fit DCPV2.
3. A license change from AGPL may be needed. DeepCreamPyV2 will drastically change the code base so switching from AGPL is not a technical problem.
4. **Monetizing DeepCreamPyV2 will ultimately lead to a better product because I will be working on the project more.**

What are your thoughts about the best ways to monetize DeepCreamPy? I am keen on hearing examples of projects with one person development teams profitable enough to sustain one person.

Opinions from contributors to DeepCreamPy are of extra importance to me.

**Comment by snakeBumble** [comment]
I am sorry to hear that.

Maybe Patreon would come in handy but i dont know that much about it.
In any case I would consider to support the Project.

**Comment by Serkan-devel** [comment]
Maybe have the trial version stick some ads into the censored areas.

**Comment by Akhliskun** [comment]
Take my wallet already :^]

**Comment by Spleeeno** [comment]
not sure about patreon, didnt they go all tumblr as in no porn allowed?
if not yet, I'm sure they will in the future.
example of patreon working for a one dev team would be dwarf fortress.
alternatives to patreon are liberapay or subscribestar afaik.

maybe make it so that the free version leaves some kind of watermark?
no idea if that would work though.

**Comment by talatuanpro** [comment]
I use V1 a lot already. Won't mind a few dollars for it.
I wouldn't recommend Patreon. It already banned a lot of user for "Adult Content". How about Liberapay?
Maybe Ads on Free ver. ? You know, like FireAlpaca?
Personally, I don't like subscription models, but it worked for many people, so there's that too.
It's just my two cents anyway.

**Comment by deeppomf** [comment]
Based on the above, there are two approaches I could take.
1. Use a crowdfunding platform like Patreon. Charge $5-10? per month to get the latest version. Have monthly updates.
DeepCreamPy should be safe on Patreon since it's not actual porn.
2. Sell it for one-time fee. Charge $10-20?. Price will increase with more updates.

Don't like free versions that mess with the output (e.g. watermark).

I think doing a Patreon AND selling for a one-time fee is overkill.

How should I handle the Japanese market? Engaging with Japan is hard because I can't speak Japanese, but there should people there interested in DeepCreamPy.

**Comment by KuroSenko96** [comment]
I've been using V1 for a long time now, and as a consumer I'm pretty impressed with what you've done and I do not mind paying to get V2 (at a reasonable price that is). Like what the other users above me said, patreon has banned "adult content" so I wouldn't recommend doing that. Instead, how about paypal or skrill.

As for the free version, I believe it would be better if you could follow what "HDoujinDownloader (HDD)" has done. "HDD" is a software where users can download doujin from supported websites. They imposed a download limit per day for the free version, and to get the premium version you'll need to make a payment to them and they'll generate a random key for you to enter into the software which will lift the download limit restriction. This way users wont be able to pirate your software even if they decide to buy and "share" online. In terms of your software, maybe you could set a limit of how many times per day the users can decensor an image for the free version. This method might persuade free users to purchase the premium version.

That's my suggestion on the best way to monetize your work. It limits piracy, and free and premium users can enjoy your content, and hopefully you get to have some in your pocket as well. Sorry to hear about your possible layoff tho, I wish you all the best in your future endeavours.

**Comment by noirscape** [comment]
I'd like to note that unless you plan on writing V2 from scratch, you'll need to get consent from all contributors to remove the AGPL license and put it under a different one.

**Comment by mwantia** [comment]
I’m a big fan of your work since the early release of DeepCreamPy and I’m amazed of what you have done so far.
Just like a lot of people already said I don’t mind paying a monthly fee for the final/premium version of DeepCreamPy. It’s a great software where a lot of work was put into so it should be no surprise that there are people who would want to “give something back”. 

So, keep up the great work and I can’t wait what the new V2 has in store for us 😊

**Comment by deeppomf** [comment]
@noirscape For the sections of the code that might be reused in DCPv2, I'll ask the contributors.
Won't be the end of the world if they refuse.

I'm happy to see the support from everyone. Was worried that some would be opposed since the license will change, but feeling more confident DCPv2 will be a success.

**Comment by Lucretious** [comment]
Hi. I am also an occasional user of your software. I like this tool, the results are really good. I wouldn´t mind to pay for your work, but I would really prefer a one time payment, as I do not use the software all that often, and feeling the need to buy a subscription for a few uses every year would feel unbalanced. 
I would also gladly pay for an update once a year, though it would be nice, if you could give a little discount for returning costumers. 
Also, I feel really sorry for your potential job-problems. That really sucks.

**Comment by Omnicron25** [comment]
Hello. I wouldn't mind paying for the new tool either, but, like Lucretious above, I am also an occasional user of this brilliant software. So, I would prefer a one-time--or at least every 6 months--payment option.

As far as thoughts on restrictions on the free version, this software is a great work, but I would probably continue to use v1--its still pretty amazing in its own right--if there are run-time restrictions on the number of images I can do at a time. However, if there were other restrictions--such as image dimension caps or input restrictions--then I would be more inclined to use it, even if a subscription payment was decided and I opted for the free version.

**Comment by Babyforce** [comment]
Hello. I do understand the need to sell this amazing piece of software, and want to say that, as an occasional user, would be ready to drop a few bucks for it (around ~10€ maybe) as a one time payement. Like the 2 person above me said, I feel like this would be better for those who use it sometimes. I also wouldn't mind paying for updates, if needed, and a little discount for those would be a huge bonus to me.

All in all, I totally agree with Lucretious, and hope that I will be able to support you this way.

**Comment by Fomortiis** [comment]
Yeah, having the software locked behind a monthly subscription will just kill off interest in people that only use it occasionally. If it was somehow my job to decensor hentai,  then a monthly subscription **could** be justified (and even then it depends on the price since you can get Photoshop for 10 bucks a month), but considering this is a piece of software that's most likely to be used occasionally rather than often, a subscription model doesn't really work. I would gladly pay once for a lifetime subscription though

**Comment by mrphax0r** [comment]
I am also an occasional user of V1, I recommend selling different versions, for example one free version for occasional users with only very basic and limited decensoring, a one-time paid version for users who take it seriously with the regular functionality, and one for ,,professional" decensoring, of course with advanced decensoring/the best you can do.
Wasn't V1 featured on /h/ a while ago?

**Comment by kogoisvo** [comment]
Hell yeah, I'd definitely pay a one-time fee for it.

**Comment by OhMyJoseph** [comment]
First off, obviously you can sell your whole product off. You can sell it to pirate website-ish places, but probably not websites that operate on user-generated contents, like pornhub, because since they don't have the right over the work, they can't decensor it and re-publish it. So selling it off is not viable way.
So you have to think about the consumer. Apparently people can easily get free uncensored hentai off from pornhub, so you have to find a reason for them to pay you. Uploading MBs or GBs of content, processing it, giving you their credit card number to pay you, and re-downloading it is a long wait time for a person who is eager to wank off to something, so you wouldn't make much if you just simply put it online.
Therefore, you have to make your way selling it to a niche of people, maybe a community, or a user group. I can't think of the exact details since I'm not exactly an expert on those forums, but do some market research.
Also, same thing if you wanna do a real-human version of it. Extra risk if you get sued by a pornstar who doesn't want her private parts decensored and shown to public.

**Comment by sanscriptum** [comment]
Imagine hentai superstar character suing you and calling you a pervert for uncensoring her privates.

**Comment by mwantia** [comment]
Well the thing here would be, that the uncensored privates aren't even her own. I mean they are "computer-generated". It's like uncensoring someone's face and replacing it with random eyes, nose and mouth. So i don't know if it's even possible to sue someone because of this.

**Comment by maddovr** [comment]
I think mantaining the AGPL license doesn't conflict with monetization. Just setup a patreon and then have people pay for builds if they're not patreon. The AGPL allows you to do that, like any Free License. Let's be perfectly honest, not everyone has the tech-savvy, especially on windows, to compile a program/make an installer. Just ship a fancy installer in a fancy static website (can be hosted for free on github) and you just have to make the link to source code visible without releasing any builds publicly. I think it's a feasible approach, while mantaining this program Free Software and forming a rather solid community. Closing up the program will let you lose community support and people may either fork the current version or just pirate the V2 if they're interested, ukuu is a lead example of a program that became proprietary and basically lost *all* support from the community.

**Comment by ccppoo** [comment]
What if selling through Steam in software section? It's easy to access and also has community hub to get bug report or suggestions from users.

**Comment by Serkan-devel** [comment]
wait, this isn't an april fools joke?

**Comment by Serkan-devel** [comment]
Maybe you can set up a [Liberapay](https://liberapay.com/) profile. They take less of a cut than Patreon and the service is FOSS as well

**Comment by DarkPulse** [comment]
As a translator and producer of English versions of manga, Eroge, and CG sets, I'd be deeply interested in V2.

I'd also absolutely hate it if I had to subscribe to it.

I have no qualms with a one-time payment, or even a new payment (ideally with discount for existing purchasers) for if there's a new major version (2, 3, etc.). But I think the ideal strategy would be:

1) One-time payment per major version of perhaps $10-20, with possibility of discounts for loyalty (buying previous versions) and/or some kind of "lifetime" license for a higher price. Assuming, of course, you're willing to work on it for long enough to justify why someone should drop, say, $40-50 for that. People will be pissed if you do V2, take the lifetime money, and run. Accept the fact there will be some piracy, too, because some people will just never want to pay. We all know of torrents by now. It's not a question of if it will get pirated - it's a question of how soon. And don't get too heavy-handed - people hate DRM. Which leads me to my next point...

2) Free version shouldn't be gimped in ways that are too harsh. No watermarks, even limits are kind of shitty, but I could see that after, say, a few dozen images or so. The idea is to strike a good balance between disincentivizing piracy of the paid version, while not bleeding yourself dry of profits from your donations/purchases. Problem is how to make it so people can't just easily reset it or they'll just find ways to get perpetual free trials and before you know it you're spending more time on defeating that than improving the program, defeating the point. Perhaps the best way would be to let it be unlimited for awhile, but after awhile (number of pictures, number of days, whatever) limit the resolution it outputs, or force output to JPG of a moderate quality loss (say 75%) - enough to visually see that yeah, it worked, but you've had plenty of time/images to try it out with, so now you can only save it as an inferior copy of the original. This way they would have to run it through Waifu2x to denoise and scale it back up, and while it will probably mostly do the trick, it will hopefully contain enough loss to make it not an appealing option, and it would destroy some of the quality in the process. (Not to mention not everyone has the hardware or the know-how to do GPU-accelerated Waifu2x.) The key isn't to really prevent it - never underestimate desperation - but to make it as annoying and unappealing as possible. Which brings me to...

3) Good software gets money not by begging for it or nagging for it, good software gets money because it's so good you WANT to give it money, and because you want to give the dev support. Support your product well, improve it the best you can, make it so that it's harder to tell it was decensored with machine algorithms than by hand, and for those people who did give you money, be reachable, be affable, and listen to them. They paid to support you and your work - your job in turn is to give them the very best product you can possibly produce. I can't stress enough the importance of speedy communications for those who gave you financial support.

4) Last, but not least: When this journey comes to an end, as all journeys must do eventually, give the community one final update - the one that opens it for all. The software is now free, here's a license key that will keep it permanently unrestricted, here's the source code and all the training data behind it, if someone else wants to pick it up go ahead, just credit me for the work I did in the past. This way even when you finally bore of this - or perhaps, no longer want to be associated with it - you can leave on good terms, in a way that will leave everyone who ever donated to you feeling good about their donation, and someone who is interested can pick up right where you left off. Don't just disappear and let licenses fade and the product to die a slow death of uselessness.

**Comment by qaisjp** [comment]
> I am keen on hearing examples of projects with one person development teams profitable enough to sustain one person.

Since you asked for examples... last I checked, the author of [Citybound[https://aeplay.org/citybound] (@aeplay) works full time on his game and his essentially a 1-man team. That might have changed since I last read his blog posts.

**Comment by agentkevin** [comment]
Is fine as long for good sake of project of community, but i hope you offer
multi payment methode for subscribe so it can help anyone who "mostly" have
payment methode issue when trying buying product.

Psa: i don't know if this help but try looking information about Danaku or
Ovo Is online payments processing like paypal but it curently for now use
in indonesian.

**Comment by deeppomf** [comment]
@DarkPulse Thank you for your thoughtful post.
One-time payment is the plan. Patreon unlikely. Schedule prevents consistent updating so people on Patreon would get nothing for their money some months, which is unfair.
If/when I stop developing DCP, I will share everything I can under a free license.

**Comment by DarkPulse** [comment]
@deeppomf Sounds good then.

Fortunately for me, summer is when I'm off of work until September, so hopefully V2 comes out fairly early during it, then I can do some test runs on some of the translation stuff I want to release during it. :)

**Comment by Ettanin1987** [comment]
Make it a cloud service with x uncensorings for free, result sent via email. For y USD a month (or a larger one time fee) the limit can be lifted.

You could make an open source version for free with the basic functionality for those that want to host on their own while extended options are only available in the cloud.

**Comment by TieSKey** [comment]
I would consider keeping it free for personal use with a nice "donate $5" button and selling comercial licences for 50+ per seat per year (depending on company size). The quality is already better than what some publishers actually release

**Comment by aeplay** [comment]
> > I am keen on hearing examples of projects with one person development teams profitable enough to sustain one person.
> 
> Since you asked for examples... last I checked, the author of [Citybound[https://aeplay.org/citybound] (@aeplay) works full time on his game and his essentially a 1-man team. That might have changed since I last read his blog posts.

lol, so this is why I kept getting notifications on this *interesting* project. I only manage to work on Citybound full-time sometimes and need to have a day job as well, but Patreon certainly helps.

@deeppomf FYI, you can set up Patreon so your Patrons pay per "release" or whatever else unit works better for you than per month.

**Comment by SirFireNewt** [comment]
You could have the source code free but the binary costs a few bucks; this lets people get it for free at the expense of downloading all the tools to compile it themselves or pay a small amount for the convenience and time save of the prebuilt.

Not sure if there are any license's that support that though
