### ISSUE TITLE
(For Linux) about file.py

### ISSUE THREAD

**Issue by ccppoo** [deeppomf/DeepCreamPy#131]
https://github.com/deeppomf/DeepCreamPy/blob/master/file.py

I recently made this to show notification for error logs and checking file formats.
But, because I'm using Windows, I'm not sure if this could make problems about difference by UPPER case and LOWER case of file name.

The reason why I raised this issue is I heard Linux count as different one , 
for example like : Hello.py != hello.py

Linux user may have different(letter case) file it could be counted as same one when file.py runs

**For someone using Linux, please check this issue using file names like Mermaid.png and mErmaid.png**

If it count as same one, changing **lower() to lowered()** will not cause problems I've expected. 
Thanks

**Comment by Wuestengecko** [comment]
```python
for file_out in output_dir:
    if file_out.lower().endswith('.png'):
        output_file_list.append(file_out)

for lhs in file_list:
    lhs.lower()
    if not lhs.lower().endswith('.png') :
        files_removed.append((lhs, 0))
    for rhs in output_file_list:
        if(lhs == rhs):
            files_removed.append((lhs, 1))
```

If I'm not mistaken, the problem here wouldn't actually be Linux honoring case but Windows ignoring it. Note that 1) you're appending the original `file_out` to the output list (and not `file_out.lower()`), and 2) the `lhs.lower()` is never assigned back to `lhs` and so is a noop. This makes `lhs == rhs` compare both file names without any case folding (as it should be on Linux), but it won't find a file `output/mErmaid.png` for the corresponding `input/Mermaid.png` on Windows.

I think the most portable approach to this would be taking the input file name (i.e. `Mermaid.png`) and trying to open a file with that name in the output directory, then catching the file-not-found error. That way the OS itself handles all the file name related stuff and you don't have to worry about it yourself.

**Comment by ccppoo** [comment]
@Wuestengecko 
Thanks, I think I wrote this with out looking it again, right after I took Linux class this thing just came from no where.
I should have think before opening the issue, sorry for my un-acknowledge

**Comment by Wuestengecko** [comment]
No worries :)
