### ISSUE TITLE
Unable to to open image file

### ISSUE THREAD

**Issue by Xlaits** [deeppomf/DeepCreamPy#143]
**DO NOT POST ADULT CONTENT**

**Describe the bug**
```
Using TensorFlow backend.
2019-05-18 20:02:08.448027: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
--------------------------------------------------------------------------
Decensoring the image ./decensor_input/cdae9d54ec678379c683f6a11d82bdae.png
Traceback (most recent call last):
  File "decensor.py", line 199, in <module>
  File "decensor.py", line 51, in decensor_all_images_in_folder
  File "site-packages\PIL\Image.py", line 2657, in open
OSError: cannot identify image file './decensor_input/cdae9d54ec678379c683f6a11d82bdae.png'
[12132] Failed to execute script decensor
```

**To Reproduce**
Running it as normal with files in the input folder

**Expected behavior**
decensoring.

**Installation method**
Binary

**Desktop (please complete the following information):**
 - OS: Windows 10 Educator
 - Version [e.g. 22] 1.3.0-Beta
 - Supports AVX? Yes

**Comment by ccppoo** [comment]
I think it's the similar problem with [this](https://github.com/deeppomf/DeepCreamPy/issues/133)

For now, the only solution is to remove that file.
Also if you casted image file format to PNG by changing name that could also trigger problem some times. 
current release version could work on other image file format.

In the next release If there's problem about opening file like this case,
decensor will skip it and continuously do the work, 
Telling which image files were skipped at the end.

**Comment by Xlaits** [comment]
The other issue was having problems with the models file. I did not change
the extension, it was a png when I downloaded it.

**Comment by ccppoo** [comment]
I can't tell exactly, can you post it or send me what you're working with? 

shmishmi79@gmail.com
or post a link to anonymous image site for privacy

**Comment by Xlaits** [comment]
> I can't tell exactly, can you post it or send me what you're working with?
> 
> [shmishmi79@gmail.com](mailto:shmishmi79@gmail.com)
> or post a link to anonymous image site for privacy

This image here: https://e621.net/post/show/1870022

**Comment by ccppoo** [comment]
thanks will give reply soon as possible

**Comment by ccppoo** [comment]
I just checked release version 1.3.0 beta win64 sse (running with Win10)
![image](https://user-images.githubusercontent.com/46418312/57995543-a54b4980-7afd-11e9-957d-a64b92b59d78.png)
and shows me nothing wrong with it without reading file
(0 censored regions doesn't matters with reading file)

did you did anything else but changing jpg to png?

**Comment by Xlaits** [comment]
> I just checked release version 1.3.0 beta win64 sse (running with Win10)
> ![image](https://user-images.githubusercontent.com/46418312/57995543-a54b4980-7afd-11e9-957d-a64b92b59d78.png)
> and shows me nothing wrong with it without reading file
> (0 censored regions doesn't matters with reading file)
> 
> did you did anything else but changing jpg to png?
> 
> Close this issue if problem is solved

I DID color the censor bars correctly, however I linked you to the original image.
Let me give you the edited image.
https://imgur.com/a/HbEIIV5

**Comment by ccppoo** [comment]
did you run this image through waifu2x?

I can't tell this could be fixed in minutes and 
it will be worked on the next release version

**Comment by Xlaits** [comment]
waifu2x? No, I just used GIMP to edit the censor bars.

**Comment by ccppoo** [comment]
![image](https://user-images.githubusercontent.com/46418312/57996609-63250680-7b03-11e9-876b-281f14099258.png)
difference between original and edited ; reason why asked

I'll find out what happens if the image run through GIMP and waifu2x
In this case I'll get a research on what makes PIL can't read from GIMP results first.

thanks for your reply

**Comment by ccppoo** [comment]
1. line that threw error
https://github.com/python-pillow/Pillow/blob/3368500f180eb14bf5b6d5b936db0eb8e084ba4d/src/PIL/Image.py#L2657

32 bit images were features of .bmp not .png (not mean there's no valid 32-bits png files, but not widely used, that's why PIL image.open throw exception I guess)
so after I converted as bmp safely by [convert_site](https://online-converting.com/image/convert2bmp/) it does 'run' but didn't work so well what you might have expected.

for decensoring precise genitals, deeppomf is working on it currently (check his(her) [tweeter](https://twitter.com/deeppomf)

I think this is all I can do for you

**Comment by Xlaits** [comment]
Honestly, the results weren't too terrible. I do have to say I have to get better at masking my censor bars, but this really was only a test.

Problem solved; closing.
