### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by namazso** [deeppomf/DeepCreamPy#186]
nvm, see third post instead

**Comment by noirscape** [comment]
The entire point of the LGPL is that it can be used as a library as long as it is not modified on it's own (in which case only the changes _to that library_ would go under the LGPL). Unlike the normal GPL there is no library linking clause in the LGPL (which is exactly why that library is written and is used for libraries). The only thing that would be needed is to link users to a place where they could see the Qt source code if requested, which is being done.

There is no license violation here. FFMPEG has a complicated licensing since it's a very old project that swapped from the GPLv2 to the LGPLv2 and as a result uses modular compilation to get around the license issues.

**Comment by namazso** [comment]
Hm, after some extra reads of the LGPLv3, you're right, I mixed it up with the vagueness of v2, and wordings explicitly asking for dynamic linking, which are better in v3. 
Although I still have some concerns:
Eula says this:
> You may not reverse engineer, decompile, or disassemble the SOFTWARE PRODUCT, except and only to the extent that such activity is expressly permitted by applicable law notwithstanding this limitation.

While LGPLv3 says:

> You may convey a Combined Work under terms of your choice that, taken together, effectively do not restrict modification of the portions of the Library contained in the Combined Work *and reverse engineering for debugging such modifications*

Maybe need an exception clause for this one too, like for linking

**Comment by deeppomf** [comment]
@namazso I will make an exception clause for reverse engineering for debugging.
