### ISSUE TITLE
Can this process be reversed (for censoring)? Is your dataset available?

### ISSUE THREAD

**Issue by kinkcoder** [deeppomf/DeepCreamPy#28]
Some people are apparently into _that_ as well. Another person and I teamed up a few days ago to train a [Yolo](https://pjreddie.com/darknet/yolo/) network to detect nudity, and then create a tool that can apply various filters (pixelation, black bars, etc.). See here for more:
https://old.reddit.com/r/Censoredforbetas/comments/9s7lnl/automated_censoring_intelligence/?st=jnuomn4h&sh=454bd6f5

So, does your network work in the other direction as well?

Alternatively, is your dataset publicly available? It could make training our network much easier.

We could also share our training data with you. We have metadata .csv/.txt files describing the coordinates for every class label for every image. Example image: https://i.imgur.com/GaFvqDZ.png

We have the following labels: BELLY_EXPOSED, BELLY_COVERED, BUTTOCKS_EXPOSED, BUTTOCKS_COVERED, FEMALE_BREAST_EXPOSED, FEMALE_BREAST_COVERED, FEMALE_GENITALIA_EXPOSED, FEMALE_GENITALIA_COVERED, MALE_GENITALIA_COVERED, MALE_GENITALIA_EXPOSED, MALE_BREAST_EXPOSED, MALE_BREAST_COVERED, FACE_FEMALE, FACE_MALE

We have two datasets, one for hentai and one for real porn.

**Comment by deeppomf** [comment]
Huh I didn't know this was a thing.

The network attempts to undo censorship and is basically the reverse of your research.

For data, look at https://www.gwern.net/Danbooru2017. My full dataset won't be publicly be available because it would get DMCA'd in an instant.

I don't think I need more data. I might have too much actually.

Best of luck! Let me know if you need any advice.
