### ISSUE TITLE
Switch to PyQt?

### ISSUE THREAD

**Issue by deeppomf** [deeppomf/DeepCreamPy#48]
Tkinter is terrible for image editing applications. The tkinter's Canvas can't export its content to a png, making built-in tools like the line tool useless. The ugly workaround is using all interactions with the Canvas to generate a PIL Image and rendering the PIL Image onto the Canvas.

With DeepCreamPy's switch to AGPL comes the option of using PyQt because PyQt can be used for free for free open source software. PyQt better supports image editing than tkinter and is better documented.

Are there any reasons why we shouldn't switch to PyQt? Are there other libraries worth considering?

**Comment by infix** [comment]
this might be an unpopular opinion but why not switch to a web based UI something like an electron app or a simple localhost server. they're pretty mature with a ton of libraries for handling user interfaces and there are a ton of resources with web available.

**Comment by Smethan** [comment]
I think an electron based UI would be interesting and definitely want to learn how to use it. I'd be happy to work on it if we go that route.

**Comment by lllyasviel** [comment]
Oh, maybe I can help you?

**Comment by Aaron2550** [comment]
A web UI would definitly be good for remote control, for example if you're decensoring a ton of images and you're not at home but want to check the status...

**Comment by Smethan** [comment]
A web UI would a be a lot easier to design, as web design is a good bit easier than window making with python, in my opinion at least. Along with that, there are a lot of really good libraries for drawing. Downsides are that we’d have to find a way to get the electron app to execute python, but I’m fairly certain that’s easily doable. I’m certain there are more downsides, but I can’t think of any atm

**Comment by firatakandere** [comment]
I kinda disagree the part web ui would be easier to design considering there's an editor in Qt for that.

**Comment by OliverFrWTFalreadyTakenComeOnNow** [comment]
Downsides? I may be wrong here because I'm waaay outside of my range, but wouldn't that exclude from using the program anyone who's unable to setup a basic LAMP on his machine? Currently, with the binary, you prepare your image, you run the .Exe and the magic operates; if it's not possible anymore because even the binary would want to rely on something third-party and a honest pain in the lower regions to setup, it would uselessly exclude people. And make it an elite-only project, kind of a waste in my eyes.
Once again: unless I misunderstood.

**Comment by Smethan** [comment]
I believe you have misunderstood. I was intending that we do an electron application as a frontend, which is essentially a website you can compile into any executable format and then run on the hosts machine as an application. Its the framework behind things like discord and slack.

**Comment by infix** [comment]
@deeppomf like @Smethan said the upsides are easier development and a wealth of tools (like react which would simplify the development process immensely) and we can reuse this UI for a remote and for creating websites while the downsides are the added complexity from maintaining 2 different stacks (Python, and JavaScript) also electron will most likely make the executable bloated since we're bundling a version of chromium with the app.

Actually the electron app might not even need to run Python since we can [load the trained model using tensorflow.js](https://js.tensorflow.org/tutorials/import-saved-model.html) and use like you normally would with python. and bundling an electron app with no python dependency will make it much easier to create a cross platform gui that just works.

**Comment by DonaldTsang** [comment]
@infix I would say that node.js has connotations that it is a ball of mud, and that PyQt or Django would work better (PHP or ruby on rails are also a possibility). But at the end of the day, DCP should create two versions of GUI: personal use and public service.

**Comment by deeppomf** [comment]
@infix The model can't be loaded with tensorflow.js because custom Keras layers aren't supported. (see https://groups.google.com/a/tensorflow.org/forum/#!msg/tfjs/yl3OZ5QeJnQ/ri3iAIs8BwAJ)

Creating the PyQt UI can be done in a few days (and sleepless nights). I want to have an updated model with better quality decensors out with a decent UI ASAP while DCP is at peak public attention. DCP's lifetime downloads yesterday were at 10k, but today they've doubled to 20k.
I'm fine with throwing away the PyQt UI for a web UI later if a web UI turns out to be better, but I think a deployable web UI won't come out soon enough while the iron is hot.

**Comment by infix** [comment]
@deeppomf i get your concern about having a UI decent ready while DCP is still trending. however i feel like with the wealth of npm packages we can hack something together faster than using PySide. if you got a mock-up i can try to implement it as soon as possible. 

@DonaldTsang yeah node has a bad reputation among other developers but i would say using web UI is easier and better than other alternatives (i only tried Qt with C++ so can't really speak for PySide) but from my experience with React i would say it should be faster and easier to implement. and we get to reuse the same codebase on both the desktop and service. this reasoning might be flawed tho so someone correct me if i'm.

**Comment by infix** [comment]
@deeppomf I would love to build an electron based UI for this project and I think I could get a prototype working tomorrow night (20:00 UTC)ish that handles most of the functionality that the current ui.py so let me know if you're interested.

**Comment by deeppomf** [comment]
@infix go for it.

**Comment by deeppomf** [comment]
@infix The basic features in the prototype UI:
-Open/save image.
-Brush tool to color image green. Adjustable brush size.
-Decensor and decensor mosaic buttons.
-Clear button that removes all green coloring.

**Comment by infix** [comment]
@deeppomf my initial suggestion of using electron didn't consider that packaging electron and python into a single stand alone executable is not trivial at all. right now I don't think that electron is a feasible solution in the short term. and i think the best course of action would be to use @HeroicKatora 's suggestion of having a server that the front end can interact with. or we can use the initial initial suggestion of using PySide/PyQt. Sorry for wasting everyone's time with my electron suggestion.

**Comment by deeppomf** [comment]
@infix It's fine. Sometimes you have to just try it out.

**Comment by irlittz** [comment]
I did [something](https://i.imgur.com/5nClHvY.png). You can find the repository [here](https://github.com/irlittz/DeepCreamPy-GUI). Because your package does not have a `setup.py`, this package has to be moved wholly to the DeepCreamPy folder and can be started with `python -m deepcreampygui`.

You can load images, save images (with the edits), zoom, scroll around, adjust the pen size, draw around, undo actions and decensor with and without the mosaic option. There's some work left: the GUI could probably look a bit nicer and it currently blocks when you click on decensor -- which can obviously be fixed with a QThread and emitting a signal when it is done. I lost the mood to do those last few cosmetic steps after working on this for a few hours. I hope someone else can finish up.

I recommend using Qt Designer to edit the *.ui files and then transpiling? them to Python files using `pyuic5`. PyQt5 is required.

**Comment by DemonInTheCloset** [comment]
@deeppomf > A reason to have an online web UI I thought of: users coloring censored regions produces ground truth for censored region location. Data could be used to train a neural network to detect censored regions automatically.

I was thinking of doing a "spot the difference" short project using censored and decensored "manga" (B&W) to do censorship detection, if i ever get it working (and done for that matter), it could work as a baseline, obviously a user-data trained model would be great...

Thinking about it, bundling a program to highlight the censored zones with DCP would get you the data and be a really cool middle-ground... I'll see what I can do...

**Comment by angus-y** [comment]
Well assuming the project isn't anything too complex and also that you still want to package everything into a single packed binary with pyinstaller, we could use a simple socket server instead for the web ui you can quickly put one together and have it serve html pages with js if needed, plus with css it'll still look pretty clean

**Comment by Stegosawr** [comment]
I mean everything is better than Tk. It's ugly.

Web Ui sounds fun.
