### ISSUE TITLE
GPU support?

### ISSUE THREAD

**Issue by 1271** [deeppomf/DeepCreamPy#76]
Hi.
Tensorflow supports GPU processing. Do you plan to add this?

Here:
https://www.tensorflow.org/guide/using_gpu#supported_devices

**Comment by Wuestengecko** [comment]
It'll automatically use your GPU if you install a GPU-enabled tensorflow (e.g. `python-tensorflow-cuda` on Arch). The PyPI / pip package is called `tensorflow-gpu`.

**Comment by 1271** [comment]
Thank you.
I will install it and check again.
Thanks for the quick response.

**Comment by sanscriptum** [comment]
Can confirm, it works at least twice as fast compared to cpu mode.  
Couple of things to note - be sure to grab the same version of ``tensorflow-gpu`` as listed in the requirements (which is ``1.10`` at the moment). Otherwise it won't work. You will also need all the CUDA stuff from nvidia and ``cudnn64_7.dll``, for which you will have to set %PATH% every time you launch DCP because it doesn't remember it for some reason (might be just my problem). The last one might be a bit painful to get because you have to register first.  
It also might hang up for a while on ``adding visible gpu devices``, just wait. That usually happens only on the first launch and later on it will be nearly instantaneous.  
This also makes me wonder if gpu version would ever be featured as a release variant @deeppomf? Since it requires all those CUDA dlls (which are heavy and nvidia doesn't like when you share them), it might not be feasible right? Unless you leave it to user to take care of.

**Comment by Wuestengecko** [comment]
If you just `SET PATH=...` in the console window, that will last until the window is closed. To make the change permanent, search for "environment variables" in the start menu (you may have to log out and back in again after changing them).

**Comment by deeppomf** [comment]
@sanscriptum the CUDA requirements are why I don't plan to do a GPU release.
