### ISSUE TITLE
an install bug about ubuntu 18.04

### ISSUE THREAD

**Issue by senior-developers** [deeppomf/DeepCreamPy#91]
Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

can you fix it? help me

**Comment by Wuestengecko** [comment]
Probably because PyYAML was pulled in by `apt` at some point. This also means that you cannot simply `apt remove` it, because something else likely depends on it.

You can try giving the `--user` flag to `pip`, that way it will install in your `$HOME`. Packages won't be available system-wide though, only for your user account. Try:

    pip install --user -r requirements.txt

Note that you must not use `sudo` in this context; also remember to pass `--user` to all other subsequent `pip` commands (and don't `sudo` them either), in case you have to do other stuff like install a different tensorflow for your CPU.
